[2024-09-15T18:13:23.608+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: table_dag.submit_tables manual__2024-09-15T18:13:14.936386+00:00 [queued]>
[2024-09-15T18:13:24.891+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: table_dag.submit_tables manual__2024-09-15T18:13:14.936386+00:00 [queued]>
[2024-09-15T18:13:24.895+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-09-15T18:13:24.924+0000] {taskinstance.py:1380} INFO - Executing <Task(PinotTableSubmitOperator): submit_tables> on 2024-09-15 18:13:14.936386+00:00
[2024-09-15T18:13:24.999+0000] {standard_task_runner.py:57} INFO - Started process 11073 to run task
[2024-09-15T18:13:25.008+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'table_dag', 'submit_tables', 'manual__2024-09-15T18:13:14.936386+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/table_dag.py', '--cfg-path', '/tmp/tmpjf5dykj1']
[2024-09-15T18:13:25.024+0000] {standard_task_runner.py:85} INFO - Job 8: Subtask submit_tables
[2024-09-15T18:13:25.119+0000] {task_command.py:415} INFO - Running <TaskInstance: table_dag.submit_tables manual__2024-09-15T18:13:14.936386+00:00 [running]> on host 035d47951d03
[2024-09-15T18:13:25.246+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='codewithyu' AIRFLOW_CTX_DAG_ID='table_dag' AIRFLOW_CTX_TASK_ID='submit_tables' AIRFLOW_CTX_EXECUTION_DATE='2024-09-15T18:13:14.936386+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-15T18:13:14.936386+00:00'
[2024-09-15T18:13:25.260+0000] {pinot_table_operator.py:35} ERROR - An error occurred: HTTPConnectionPool(host='pinot-controller', port=9000): Max retries exceeded with url: /tables (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff7fa6d3a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-09-15T18:13:25.281+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=table_dag, task_id=submit_tables, execution_date=20240915T181314, start_date=20240915T181323, end_date=20240915T181325
[2024-09-15T18:13:25.317+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-09-15T18:13:25.339+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
