[2024-09-19T18:13:46.134+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-09-17T00:00:00+00:00 [queued]>
[2024-09-19T18:13:46.743+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-09-17T00:00:00+00:00 [queued]>
[2024-09-19T18:13:46.774+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-09-19T18:13:48.483+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): generate_customer_dim_data> on 2024-09-17 00:00:00+00:00
[2024-09-19T18:13:49.559+0000] {standard_task_runner.py:57} INFO - Started process 426 to run task
[2024-09-19T18:13:51.110+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'customer_dim_generator', 'generate_customer_dim_data', 'scheduled__2024-09-17T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/customer_dim_generator.py', '--cfg-path', '/tmp/tmp5fkn22it']
[2024-09-19T18:13:51.345+0000] {standard_task_runner.py:85} INFO - Job 36: Subtask generate_customer_dim_data
[2024-09-19T18:13:58.383+0000] {task_command.py:415} INFO - Running <TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-09-17T00:00:00+00:00 [running]> on host 48913e9acee9
[2024-09-19T18:14:14.208+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 36 for task generate_customer_dim_data (UPDATE statement on table 'task_instance' expected to update 1 row(s); 0 were matched.; 426)
[2024-09-19T18:14:16.678+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-09-19T18:23:35.090+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-09-17T00:00:00+00:00 [queued]>
[2024-09-19T18:23:35.151+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-09-17T00:00:00+00:00 [queued]>
[2024-09-19T18:23:35.153+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-09-19T18:23:35.219+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): generate_customer_dim_data> on 2024-09-17 00:00:00+00:00
[2024-09-19T18:23:35.264+0000] {standard_task_runner.py:57} INFO - Started process 221 to run task
[2024-09-19T18:23:35.267+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'customer_dim_generator', 'generate_customer_dim_data', 'scheduled__2024-09-17T00:00:00+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/customer_dim_generator.py', '--cfg-path', '/tmp/tmpu4ly6cew']
[2024-09-19T18:23:35.295+0000] {standard_task_runner.py:85} INFO - Job 48: Subtask generate_customer_dim_data
[2024-09-19T18:23:35.760+0000] {task_command.py:415} INFO - Running <TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-09-17T00:00:00+00:00 [running]> on host 48913e9acee9
[2024-09-19T18:23:36.189+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='codewithyu' AIRFLOW_CTX_DAG_ID='customer_dim_generator' AIRFLOW_CTX_TASK_ID='generate_customer_dim_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-17T00:00:00+00:00'
[2024-09-19T18:23:36.219+0000] {logging_mixin.py:151} INFO - CSV file './customer_dim_large_data.csv' with 100 rows has been generated successfully.
[2024-09-19T18:23:36.220+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-09-19T18:23:36.241+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=customer_dim_generator, task_id=generate_customer_dim_data, execution_date=20240917T000000, start_date=20240919T182335, end_date=20240919T182336
[2024-09-19T18:23:36.296+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-09-19T18:23:36.375+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
