[2024-09-15T17:00:13.040+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: table_dag.submit_tables manual__2024-09-15T17:00:04.065288+00:00 [queued]>
[2024-09-15T17:00:13.188+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: table_dag.submit_tables manual__2024-09-15T17:00:04.065288+00:00 [queued]>
[2024-09-15T17:00:13.193+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-09-15T17:00:14.806+0000] {taskinstance.py:1380} INFO - Executing <Task(PinotTableSubmitOperator): submit_tables> on 2024-09-15 17:00:04.065288+00:00
[2024-09-15T17:00:14.888+0000] {standard_task_runner.py:57} INFO - Started process 5198 to run task
[2024-09-15T17:00:14.904+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'table_dag', 'submit_tables', 'manual__2024-09-15T17:00:04.065288+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/table_dag.py', '--cfg-path', '/tmp/tmpaiqndfgb']
[2024-09-15T17:00:14.976+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask submit_tables
[2024-09-15T17:00:24.311+0000] {task_command.py:415} INFO - Running <TaskInstance: table_dag.submit_tables manual__2024-09-15T17:00:04.065288+00:00 [running]> on host 035d47951d03
[2024-09-15T17:00:25.034+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='codewithyu' AIRFLOW_CTX_DAG_ID='table_dag' AIRFLOW_CTX_TASK_ID='submit_tables' AIRFLOW_CTX_EXECUTION_DATE='2024-09-15T17:00:04.065288+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-15T17:00:04.065288+00:00'
[2024-09-15T17:00:26.184+0000] {pinot_table_operator.py:35} ERROR - An error occurred: HTTPConnectionPool(host='pinot-controller', port=9000): Max retries exceeded with url: /tables (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff7fae33d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-09-15T17:00:26.302+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=table_dag, task_id=submit_tables, execution_date=20240915T170004, start_date=20240915T170013, end_date=20240915T170026
[2024-09-15T17:00:26.536+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-09-15T17:00:26.837+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
