[2024-09-15T18:22:40.703+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: table_dag.submit_tables manual__2024-09-15T18:22:02.239995+00:00 [queued]>
[2024-09-15T18:22:41.064+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: table_dag.submit_tables manual__2024-09-15T18:22:02.239995+00:00 [queued]>
[2024-09-15T18:22:41.065+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-09-15T18:22:41.081+0000] {taskinstance.py:1380} INFO - Executing <Task(PinotTableSubmitOperator): submit_tables> on 2024-09-15 18:22:02.239995+00:00
[2024-09-15T18:22:41.106+0000] {standard_task_runner.py:57} INFO - Started process 11707 to run task
[2024-09-15T18:22:41.115+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'table_dag', 'submit_tables', 'manual__2024-09-15T18:22:02.239995+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/table_dag.py', '--cfg-path', '/tmp/tmp2_xltqwn']
[2024-09-15T18:22:41.120+0000] {standard_task_runner.py:85} INFO - Job 12: Subtask submit_tables
[2024-09-15T18:22:41.185+0000] {task_command.py:415} INFO - Running <TaskInstance: table_dag.submit_tables manual__2024-09-15T18:22:02.239995+00:00 [running]> on host 035d47951d03
[2024-09-15T18:22:41.285+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='codewithyu' AIRFLOW_CTX_DAG_ID='table_dag' AIRFLOW_CTX_TASK_ID='submit_tables' AIRFLOW_CTX_EXECUTION_DATE='2024-09-15T18:22:02.239995+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-15T18:22:02.239995+00:00'
[2024-09-15T18:22:41.293+0000] {pinot_table_operator.py:35} ERROR - An error occurred: HTTPConnectionPool(host='pinot-controller', port=9000): Max retries exceeded with url: /tables (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff7fa044c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-09-15T18:22:41.299+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=table_dag, task_id=submit_tables, execution_date=20240915T182202, start_date=20240915T182240, end_date=20240915T182241
[2024-09-15T18:22:41.340+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-09-15T18:22:41.353+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
